# Generated by Django 4.0 on 2024-04-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('Barishal', 'Barishal'), ('Chattogram', 'Chattogram'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet')], max_length=50, unique=True)),
                ('district', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolytechnicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('institute_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=15)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polytechnic_location', to='Polytechnic.locationmodel')),
            ],
        ),
    ]
