# Generated by Django 4.0 on 2024-04-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polytechnic', '0002_alter_locationmodel_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='district',
            field=models.CharField(max_length=150),
        ),
    ]
