# Generated by Django 4.0 on 2024-04-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
        ('Polytechnic', '0003_alter_locationmodel_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_student', models.IntegerField(default=0)),
                ('total_softmax_student', models.IntegerField(default=0)),
                ('duetian_teacher', models.IntegerField(default=0)),
                ('department_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_detail', to='Department.departmentmodel')),
                ('polytechnic_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polytechnic_detail', to='Polytechnic.polytechnicmodel')),
            ],
        ),
    ]
