# Generated by Django 5.0.3 on 2024-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=10)),
            ],
        ),
    ]
